"""
Central configuration for ZaloPay Stock Intelligence Agent.
"""
import os, sqlite3, tempfile, base64
from pathlib import Path
from dotenv import load_dotenv

# Load .env from project root
BASE_DIR = Path(__file__).parent
load_dotenv(BASE_DIR / ".env")


def _env(name: str, default: str = "") -> str:
    """
    Read an env var, preferring a base64-encoded `<NAME>_B64` variant if set.

    The AgentBase Runtime's env injection fails to start the pod when a value
    contains certain characters (e.g. '@' in email/SMTP credentials). Supplying
    such secrets base64-encoded as `<NAME>_B64` sidesteps that — this helper
    transparently decodes them, so the rest of the app is unchanged.
    """
    b64 = os.getenv(name + "_B64")
    if b64:
        try:
            return base64.b64decode(b64).decode("utf-8")
        except Exception:
            pass
    return os.getenv(name, default)

# ── IMAP (email reading) ───────────────────────────────────────────────────
IMAP_HOST     = _env("IMAP_HOST", "outlook.office365.com")
IMAP_PORT     = int(_env("IMAP_PORT", "993"))
IMAP_USER     = _env("IMAP_USER", "anhdp5@vng.com.vn")
IMAP_PASSWORD = _env("IMAP_PASSWORD", "")

# ── SMTP ───────────────────────────────────────────────────────────────────
SMTP_HOST     = _env("SMTP_HOST", "smtp.office365.com")
SMTP_PORT     = int(_env("SMTP_PORT", "587"))
SMTP_USER     = _env("SMTP_USER", "")
SMTP_PASSWORD = _env("SMTP_PASSWORD", "")

# ── Report recipients ──────────────────────────────────────────────────────
REPORT_RECIPIENTS = [
    r.strip() for r in _env("REPORT_RECIPIENTS", "anhdp5@vng.com.vn").split(",")
]

# ── Storage ────────────────────────────────────────────────────────────────

def _resolve_db_path() -> Path:
    """
    Try the default DB path. Fall back to /tmp if stale journal blocks writes.
    """
    candidate = BASE_DIR / os.getenv("DB_PATH", "data/market_intelligence.db")
    try:
        candidate.parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(str(candidate))
        conn.execute("CREATE TABLE IF NOT EXISTS _probe (id INTEGER PRIMARY KEY)")
        conn.execute("INSERT OR REPLACE INTO _probe VALUES (1)")
        conn.commit()
        conn.close()
        return candidate
    except Exception as exc:
        fallback = Path(tempfile.gettempdir()) / "market_intelligence.db"
        import logging
        logging.getLogger("config").warning(
            "DB %s blocked (%s). Using fallback: %s", candidate, exc, fallback
        )
        return fallback

DB_PATH     = _resolve_db_path()
REPORTS_DIR = BASE_DIR / "reports"

# ── Scheduler ─────────────────────────────────────────────────────────────
REPORT_TIME = os.getenv("REPORT_TIME", "08:00")
TIMEZONE    = os.getenv("TIMEZONE", "Asia/Ho_Chi_Minh")

# ── LLM (GreenNode AI Platform, OpenAI-compatible) ──────────────────────────
# Insights & recommendations are generated by this model; if the key is unset
# or a call fails, the engine falls back to the deterministic rule-based logic.
LLM_API_KEY  = os.getenv("LLM_API_KEY", "")
LLM_MODEL    = os.getenv("LLM_MODEL", "qwen/qwen3-5-27b")
LLM_BASE_URL = os.getenv("LLM_BASE_URL", "https://maas-llm-aiplatform-hcm.api.vngcloud.vn/v1")
LLM_TIMEOUT  = int(os.getenv("LLM_TIMEOUT", "120"))

# ── Data sources ───────────────────────────────────────────────────────────
CAFEF_BASE_URL     = "https://cafef.vn"
CAFEF_MARKET_URL   = "https://cafef.vn/du-lieu.chn"
DNSE_SENDER_EMAIL  = "metabase@mail.dnse.com.vn"
LOOKBACK_DAYS      = 30   # calendar days to collect
ANALYSIS_WINDOW    = 7    # trading days for analytics
WEEK_TRADING_DAYS  = 5    # trading days in one week (markets closed on weekends)

# ── ZLP metric key mapping (legacy, kept for reference) ───────────────────
ZLP_EMAIL_METRICS = {
    "ZLP_NewAccount":        "ZLPNewAccount",
    "ZLP_Transaction":       "ZLPTransaction",
    "ZLP_ActiveUsers":       "ZLPActiveUsers",
    "ZLP_ActiveSellUsers":   "ZLPActiveSellUsers",
    "ZLP_ActiveBuyUsers":    "ZLPActiveBuyUsers",
    "ZLP_ActiveUsersMonthly":"ZLPActiveUsersMonthly",
}

# Vietnamese public holidays (YYYY-MM-DD) to skip in trading-day logic
VN_HOLIDAYS_2024_2026 = {
    # 2024
    "2024-01-01", "2024-02-08", "2024-02-09", "2024-02-10",
    "2024-02-11", "2024-02-12", "2024-02-13", "2024-02-14",
    "2024-04-18", "2024-04-30", "2024-05-01", "2024-09-02",
    # 2025
    "2025-01-01", "2025-01-27", "2025-01-28", "2025-01-29",
    "2025-01-30", "2025-01-31", "2025-02-01", "2025-02-02",
    "2025-04-07", "2025-04-30", "2025-05-01", "2025-09-01", "2025-09-02",
    # 2026
    "2026-01-01", "2026-02-16", "2026-02-17", "2026-02-18",
    "2026-02-19", "2026-02-20", "2026-02-21", "2026-02-22",
    "2026-04-17", "2026-04-30", "2026-05-01", "2026-09-02",
}
